name: PHP Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        phpVersion: ['8.3', '8.4']

    container:
      image: danny60072/gitlab-ci-pipeline-php:${{ matrix.phpVersion }}-node22
      options: --user 1001

    services:
      db:
        image: apache/age:release_PG15_1.5.0
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.phpVersion }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Test
      run: composer run test

    - name: Phpstan
      run: composer run phpstan

    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml
        verbose: true
